{% set name = "py-bip39-bindings" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/polkascan/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 49187bd49299bdcc3708fbe4fafa78ffba0fa6505a56e4fd09a33189d754fd95

build:
  script_env:
    - PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin =0.14.17
    - pip
    - python
    - setuptools-rust
  run:
    - python

test:
  source_files:
    - tests.py
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest -v tests.py
  downstreams:
    - py-sr25519-bindings
    - py-ed25519-zebra-bindings

about:
  home: https://github.com/polkascan/py-bip39-bindings
  summary: 'Python bindings for the tiny-bip39 library: https://crates.io/crates/tiny-bip39'
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - arjanz
    - MementoRC
