{% set name = "py-bip39-bindings" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/polkascan/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ea989a606dec90e1c9a8b668ac9d5a7388141cd973d665d8b28caa000552c76c
  patches:
    - fix-Cargo-pep621.patch
    - fix-pyproject-pep621.patch

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vvv
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin =0.14.17
    - pip
    - python
    - setuptools-rust
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  source_files:
    - tests.py
  requires:
    - pytest
    - python
    - pip
  commands:
    - pip check
    - python -m pytest -v tests.py
  downstreams:
    - py-sr25519-bindings
    - py-ed25519-zebra-bindings

about:
  home: https://github.com/polkascan/py-bip39-bindings
  summary: 'Python bindings for the tiny-bip39 library: https://crates.io/crates/tiny-bip39'
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - MementoRC
