{% set name = "py-bip39-bindings" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/polkascan/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: de4def747bea7fd4eb7f7b1d75eaa60a09c2598f0612bbae87231696ab594586

build:
  script_env:
    - PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin =0.14.17  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - maturin =0.14.17
    - pip
    - python
    - setuptools-rust
  run:
    - python

test:
  source_files:
    - tests.py
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest -v tests.py
  # downstreams:
  #   - py-sr25519-bindings
  #   - py-ed25519-zebra-bindings

about:
  home: https://github.com/polkascan/py-bip39-bindings
  summary: 'Python bindings for the tiny-bip39 library: https://crates.io/crates/tiny-bip39'
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - arjanz
    - MementoRC
