{% set name = "py-bip39-bindings" %}
{% set sha256 = "ea989a606dec90e1c9a8b668ac9d5a7388141cd973d665d8b28caa000552c76c" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/polkascan/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vvv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin =0.14.0
    - python
    - pip
    - setuptools-rust
  run:
    - python

test:
  source_files:
    - tests.py
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest -v tests.py

about:
  home: https://github.com/polkascan/py-bip39-bindings
  summary: 'Python bindings for the tiny-bip39 library: https://crates.io/crates/tiny-bip39'
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - MementoRC
